spring.application.name=payment-service
server.port=8086

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always